### ISSUE TITLE
Unable to define channel name in 1_PrepareTilesMIST.ijm

### ISSUE THREAD

**Issue by JeroenJacques** [lukasvandenheuvel/CellContactNetwork#1]
In [1_PrepareTilesMIST.ijm](https://github.com/lukasvandenheuvel/CellContactNetwork/blame/main/Stitching/1_PrepareTilesMIST.ijm) the user is requested to specify the number of channels that need to be processed. However, if you choose only 1 channel, it will look for filenames containing `d0`. If your file names do not contain this exact part, an error will be raised. 

`
// Check if the inputted number of channels is correct
	last_ch_file = input_folder + q + get_img_file_name(file0, well, 0, nr_channels-1);
	one_file_too_far = input_folder + q + get_img_file_name(file0, well, 0, nr_channels);
	if (!File.exists(last_ch_file)){
		exit("Sorry, the chosen number of channels of "+d2s(nr_channels,0)+" cannot be correct. \nFound less than "+d2s(nr_channels,0)+" channels in the input folder of well "+well+".");
	}
	if (File.exists(one_file_too_far)){
		exit("Sorry, the chosen number of channels of "+d2s(nr_channels,0)+" cannot be correct. \nFound more than "+d2s(nr_channels,0)+" channels in the input folder of well "+well+".");
	`

It would be more convenient if the user can specify which channels to process and which not.

**Comment by lukasvandenheuvel** [comment]
Thanks! With the updated version, you should be able to select which channels you want to be processed. Also, you now have the possibility to define a filename format in 1_PrepareTilesMIST.ijm, s.t. you can process files with names distinct from the default HCA output. See the documentation [here](https://lukasvandenheuvel.github.io/CellContactNetwork/stitching.html).
